name: NPM Publish From Label

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
      - closed

permissions:
  contents: read
  pull-requests: write

jobs:
  npm-publish-from-label:
    uses: infrastructure-blocks/npm-publish-from-label-workflow/.github/workflows/workflow.yml@v1
    secrets:
      github-pat: ${{ secrets.PAT }}
      npm-token: ${{ secrets.NPM_PUBLISH_TOKEN }}
